In [1]:
from csv import DictReader

In [2]:
fp = open("podatki/stockholm.csv", "rt")
reader = DictReader(fp)

for row in reader:
    print(row)
    break

OrderedDict([('Year', '1800'), ('Month', '1'), ('Day', '1'), ('Temp', '-6.1')])


In [4]:
import numpy as np
np.set_printoptions(suppress=True)

data = np.loadtxt("podatki/stockholm.csv", delimiter=",", skiprows=1)
data

array([[1800. ,    1. ,    1. ,   -6.1],
       [1800. ,    1. ,    2. ,  -15.4],
       [1800. ,    1. ,    3. ,  -15. ],
       ...,
       [2011. ,   12. ,   29. ,    4.9],
       [2011. ,   12. ,   30. ,    0.6],
       [2011. ,   12. ,   31. ,   -2.6]])

In [5]:
data.shape

(77431, 4)

In [8]:
data[(data[:, 0] == 2011), :]

array([[2011. ,    1. ,    1. ,   -2.3],
       [2011. ,    1. ,    2. ,   -3.6],
       [2011. ,    1. ,    3. ,   -6.9],
       ...,
       [2011. ,   12. ,   29. ,    4.9],
       [2011. ,   12. ,   30. ,    0.6],
       [2011. ,   12. ,   31. ,   -2.6]])

In [7]:
data[(data[:, 0] == 1817) * (data[:, 1] == 12) * (data[:, 2] == 5), :]

array([[1817. ,   12. ,    5. ,   -5.8]])

In [9]:
np.mean(data[:, 3])

6.197109684751585

In [14]:
np.mean(data[(data[:, 1] == 1), 3])

-3.0447656725502132