In [4]:
import numpy as np

In [22]:
a = np.array([1, 2, 3], dtype="int32")
print(a)

[1 2 3]


In [8]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
# Get dimentions
a.ndim
b.ndim

2

In [15]:
# Get Shape
b.shape

(2, 3)

In [23]:
a.dtype

dtype('int32')

In [24]:
a.itemsize

4

In [ ]:
# Get total size
a.size * a.itemsize

# Dostopanje/spreminjanje elementov, vrstic, stolpcev, ...

In [26]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [29]:
# Get a specific element [r, c]
a[1, 5]

13

In [30]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [33]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [37]:
a[1, 5] = 20
print(a)

a[:, 2] = [1, 2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [39]:
# 3d example
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [40]:
# Get specific element (work outside in)
b[0, 1, 1]

4

In [41]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [43]:
b[:, 1, :] = [[9,9], [8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

# Različne vrste polj

In [45]:
# All 0s matrix
np.zeros((2, 3, 3, 2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [47]:
# All 1s matrix
np.ones((4, 2, 2), dtype="int32")

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [49]:
# Any other number
np.full((2,2), 99, dtype="float32")

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [50]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [52]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.04696644, 0.68714084],
       [0.4880273 , 0.72230072],
       [0.24950626, 0.30912493],
       [0.08511936, 0.93282083]])

In [53]:
# Random Integer values
np.random.randint(7, size=(3,3))

array([[2, 0, 2],
       [3, 4, 4],
       [3, 3, 4]])